# This is a sample build configuration for Java (Gradle).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
#image: openjdk:8
#image: bitbucketpipelines/android-ci-image
#image: mingc/android-build-box:latest > https://awesomeopensource.com/project/mingchen/docker-android-build-box
#image: thyrlian/android-sdk
image: androidsdk/android-30:latest

pipelines:
  branches:
    feature/spike/bitbucket-pipelines:
      - step:
          name: DebugBuild DachApp
         
          caches:
            - gradle
            - gradle-wrapper
            - android-emulator

          script: # Modify the commands below to build your repository.
            # You must commit the Gradle wrapper to your repository
            # https://docs.gradle.org/current/userguide/gradle_wrapper.html
            
            - yes | sdkmanager --licenses

            - unset ANDROID_NDK_HOME # To unset the NDK env if not needed

            - echo -n "$KEY_ALIAS_CONCLUTEC"
            - echo -n "$KEY_ALIAS_SOLUTIANCE"
            - echo "$JKS_FILE_CONCLUTEC" | base64 -d > conclutec.keystore.jks
            - echo "$JKS_FILE_SOLUTIANCE" | base64 -d > solutiance.keystore.jks
            - md5sum conclutec.keystore.jks
            - md5sum solutiance.keystore.jks

            # We can only use arm-images and at the moment (15.01.2021) there is no newer image avaiable.
            # Check available SDKs with 'sdkmanager --list'
            #- sdkmanager "system-images;android-25;google_apis;armeabi-v7a"
            - sdkmanager "system-images;android-29;google_apis_playstore;x86"
            - sleep 60
            #- echo "no" | avdmanager create avd -n avdRealmTests -k "system-images;android-25;google_apis;armeabi-v7a"
            - echo "no" | avdmanager create avd -n avdRealmTests -k "system-images;android-29;google_apis_playstore;x86"
            - sleep 5
            - adb start-server
            - adb devices
            - emulator -avd avdRealmTests -no-audio -no-window -no-boot-anim -gpu off &
            - adb wait-for-device
            - adb devices

            - sleep 120

            - adb connect 127.0.0.1:5555
            - ./gradlew -DconnectedAndroidTest.single=LandingActivityTests connectedAndroidTest

            # Crearting signed APKs is not working yet :(
            #- ./gradlew assembleDevelopRelease
            #artifacts:
            #- app/build/outputs/**

definitions:
  caches:
    gradle-wrapper: ~/.gradle/wrapper
    android-emulator: $ANDROID_HOME/system-images/android-25
