name: Instrumentation Tests

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name when a job name is not provided
  instrumentationTests:
    name: InstrumentationTests
    runs-on: macos-10.15
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    #- name: Validate build
    #  run: ./gradlew assemble

    - name: Change script permissions
      run: chmod +x ./github_action_emulator_command.sh

    - name: Run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        profile: pixel_3a
        script: ./github_action_emulator_command.sh connectedDevelopDebugAndroidTest

    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
        name: insrumentation-test-results
        path: ./**/build/reports/androidTests/connected/**